### ISSUE TITLE
TODO list etc?

### ISSUE THREAD

**Issue by ng-0** [llambda/nary#2]
This seems interesting and more recent compared to the other js package manager rewrites.

Do you keep a TODO list somewhere which could be published?
What are you aiming for here, a full yarn replacement, or what is your definition of done per design?

**Comment by llambda** [comment]
Thanks! It is mostly experimental for now so no particular goals or ambitions yet. It does kind of work though.

**Comment by llambda** [comment]
Added notes to README.
